### ISSUE TITLE
Freyr

### ISSUE THREAD

**Issue by ChristoffBo** [RandomNinjaAtk/arr-scripts#124]
Freyr, Failed to Detect an Internet Connection

**Comment by RandomNinjaAtk** [comment]
Sounds like a client issue or a user configuration issue. These scripts are the glue that just makes it all work, if its a problem with a particular piece of software, you'll need to address that upstream. Keep in mind, you should do more testing to verify where the problem is...

If you can prove that the scripts are causing an issue, then it's something I could possibly look into if you can provide proper evidence to identify/prove/reproduce the problem. However, these scripts simply pass information to each respective client, so I don't suspect it's a problem with the automation scripts...

**Comment by ChristoffBo** [comment]
Hi, yes seems to be an issue with freyr set the d3fault.x4p to net check
false will monitor. Thanks.

**Comment by ChristoffBo** [comment]
sorry last question, you dont know where in these scripts i can add --no-net-check to freyer?

if i manually run it with that at the end ir goes through.

**Comment by RandomNinjaAtk** [comment]
Let me know if this does the job: https://github.com/RandomNinjaAtk/arr-scripts/commit/425c59e06c17fe006bbfc26cb4ef68c69249fc43

**Comment by ChristoffBo** [comment]
So i just need to restart my lidarr docker and it should make the changes?

**Comment by RandomNinjaAtk** [comment]
@ChristoffBo Yes

**Comment by ChristoffBo** [comment]
running now. Thank you Sir!

**Comment by RandomNinjaAtk** [comment]
So this is resolved?

**Comment by ChristoffBo** [comment]
yes, thank you
