### ISSUE TITLE
Sonarr [custom-init] scripts_init.bash: exited 127

### ISSUE THREAD

**Issue by WillScott73** [RandomNinjaAtk/arr-scripts#15]
The script_init.bash script is failing. None of the files that it attempts to download have been. Permissions on all folders are set to 0777

───────────────────────────────────────
[custom-init] Files found, executing
[custom-init] scripts_init.bash: executing...
/custom-cont-init.d/scripts_init.bash: line 2: $'bash\r': command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20  4106   20   826    0     0   3211      0  0:00:01 --:--:--  0:00:01  3201
curl: (23) Failure writing output to destination
[custom-init] scripts_init.bash: exited 127

**Comment by RandomNinjaAtk** [comment]
Seems like your having a technical problem maybe network related that is unrelated to this... because it's not reproducible and it's something wrong with your particular environment.

You'll have to investigate more and fix it. There is nothing to be done on this end because it's been confirmed as working for multiple users.
