### ISSUE TITLE
[FEATURE] - Radarr/Sonarr - Multiple languages for downloading videos

### ISSUE THREAD

**Issue by Druidblack** [RandomNinjaAtk/arr-scripts#210]
**Is your feature request related to a problem? Please describe.**
Only one language profile is selected to download trailers for movies and TV series

**Describe the solution you'd like**
I would like to be able to specify several languages for downloading video materials in the configuration file settings.
With priority for uploading videos in the desired language. And the ability to update the trailer to the priority language if the trailer was previously uploaded in English (the default language).

**Comment by RandomNinjaAtk** [comment]
It already supports multiple languages, it’s a comma separated list… as it says in the config description.

it does not give any kind of priority and honestly that wouldn’t really be possible unless the files all had the same name regardless of language which is highly unlikely. The script doesn’t exactly manage the data… If this was an actual application to manage these files, your request would make more sense because the files would then be tracked, managed and could more likely achieve what your looking for by priority.
