### ISSUE TITLE
[FEATURE] - Lidarr - Choosing one filetype for quality

### ISSUE THREAD

**Issue by bonelifer** [RandomNinjaAtk/arr-scripts#246]
**Is your feature request related to a problem? Please describe.**
Can we choose to only support downloading MP3's, instead of M4A's.  I  may just don't understand Lidarr enough.

**Comment by RandomNinjaAtk** [comment]
The scripts only download in the quality available, and it will only convert uncompressed files to a desired format when enabled.... My guess is that your using freyr client, which only supports M4A file type. So if you want a different quality, you have to consider changing how your sourcing it, instead of the current method/configuration. It's possible to do what you want, but now based on how your using it.

**Comment by RandomNinjaAtk** [comment]
Try enabling "requireQuality" by setting it to true, to see if that resolves your issue.
