### ISSUE TITLE
Migrate from previous containers you created

### ISSUE THREAD

**Issue by MARAllMighty** [RandomNinjaAtk/arr-scripts#26]
Hello there,

Can you please provide instructions on how to migrate from using your previous containers to these scripts? 

This is the second time you have abandoned your previous projects and pushed users into a new repo without instructions on how to migrate and it's becoming challenging to trust that you won't drop this one like the others.

Because of how good your original script was, I made the jump to your Extended containers and now it's jumping again...

**Comment by RandomNinjaAtk** [comment]
I honestly don't have to justify anything but for some of the reasons, you can find here:
https://github.com/RandomNinjaAtk/arr-scripts/issues/3#issuecomment-1629751218

**Comment by RandomNinjaAtk** [comment]
You can almost just swap the image for linuxserver.io's (develop) image for each container.

So what you'll do is:
1. Change to the official image (develop tag)
1. Delete/remove the entire contents of /config/extended directory
1. Follow the installation instructions: https://github.com/RandomNinjaAtk/arr-scripts#usage
1. Configure the config file to match your previous configuration.

I would recommend that you disable auto-configure, because it will override your settings.
