### ISSUE TITLE
[FEATURE] - Radarr/Sonarr - Update support for dotnet8

### ISSUE THREAD

**Issue by tboucher204** [RandomNinjaAtk/arr-scripts#264]
**Is your feature request related to a problem? Please describe.**
dotnet8 is not supported in Alpine 3.20 and will become an issue for anyone updating Sonarr and Radarr after May 31, 2024.  Linuxserver.io rebased to Alpine 3.20 on May 31st and Alpine has dropped support for dotnet7 starting with 3.20.  Your setup.bash is configured to install dotnet7, which means it will not be able to find it and errors occur after that because dotnet is no longer available.

**Describe the solution you'd like**
If your arr-scripts can support dotnet8, just update the setup.bash to install that version.  Otherwise, check into updating the scripts to support dotnet8.

**Describe alternatives you've considered**
The only alternative I have tried is specifying a specific Radarr version prior to the rebase by Linuxserver.io.  I suppose, I could also just create my own setup.bash which would use dotnet8 but have not tried that.

**Additional context**
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/17454305/95b5970f-2d35-4866-83d6-1385ef598da0)

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/17454305/52e8629b-e913-463e-91b7-7e82cd829e01)

**Comment by RandomNinjaAtk** [comment]
These are just scripts take your issue upstream….

**Comment by beaver-coder** [comment]
This guy actually was on to something, but I figured out the issue.

In the setup.bash file for sonarr-extended and radarr-extended, you have a call for:

"http://dl-cdn.alpinelinux.org/alpine/edge/community dotnet7-runtime"

dotnet7-runtime no longer exists for alpine linux. This needs to be updated to:

http://dl-cdn.alpinelinux.org/alpine/edge/community dotnet8-runtime

I forked it, and it fixed the issue for me. Recyclarr would not run otherwise.

I opened pull requests to fix this is sonarr and radarr:

#293 and #294

**Comment by RandomNinjaAtk** [comment]
@beaver-coder  PR's merged and resolved this request
