### ISSUE TITLE
[BUG] - Lidarr - Downloads over and over

### ISSUE THREAD

**Issue by Varming73** [RandomNinjaAtk/arr-scripts#290]
**Application**
Lidarr 2.4.3.4248

**Host platform**
Unraid 6.12.6

**Describe the bug**
All albums are downloaded over and over again. The same albums seem to download from the same services all the time.

**Additional context**
Please ask for what you need, I don't know which log files are relevant.

**Comment by RandomNinjaAtk** [comment]
Sounds like an issue with your lidarr configuration, possibly your cutoff settings and etc. The scripts only do what Lidarr informs it to do... 

So for example, if you set your cutoff to FLAC 24bit, and most stuff is not 24bit, unfortunately the script has no idea what the quality is... So it can theoretically keep re-trying because lidarr always has the album as wanted...

So this would not be a bug, but a user misconfiguration...

**Comment by Varming73** [comment]
Ah - that is actually quite possible, I didn't think of that. I will test asap.

**Comment by Varming73** [comment]
You were absolutely right, @RandomNinjaAtk - that solved it. It was my cutoff that I had set wrong. Thanks a lot for you help!
