### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by karbowiak** [RandomNinjaAtk/arr-scripts#3]
Hi @RandomNinjaAtk 

I noticed you deprecated and removed the images for the other containers, which was a bit of a bad timing, since i was setting up stuff 😅 

So i threw myself into this, since i could see you were actively working on the various scripts - but i can't seem to figure out what images you're using to run it all in, since the linuxserver.io ones are using ubuntu apparently 😅 

If it's purely for internal use, that's fine i'll figure something out, if not - need a tester? 😄

**Comment by RandomNinjaAtk** [comment]
These are all for linuxserver images. I will possibly post some documentation. I retired the other projects because I no longer want to pay for container builds and frankly all I was doing was seamlessly packaging it. But it caused support nightmares for the devs of the apps and support issues were troublesome at times. So elminating the containers means no more headaches....

Also I mostly wrote these scripts for myself. So moving away from a managed container means less overhead and less support issues.

However, on that note, Sonarr/Radarr/Sabnzbd are working though... and Lidarr is still a work in-progress. Keep in mind, everything is configured for how I use it, no options to make changes and etc. 

The basic setup if you want to use them is:

1. You need to add 2 volumes (docker run example):
`-v /path/to/preferred/local/directory:/custom-services.d`
`-v /path/to/preferred/local/directory:/custom-cont-init.d`
1. Download the scripts_init.bash (Example: https://github.com/RandomNinjaAtk/arr-scripts/blob/main/radarr/scripts_init.bash) for the respective app and place it in the following volume:
`-v /path/to/preferred/local/directory:/custom-cont-init.d`
1. Start the container and wait for application to fully start, services will not start until the container is restarted...
1. Restart the container and the services should kick off successfully

You are welcome to test and provide feedback, making it configurable might be a goal in the future. But I'm trying to streamline everything and reduce support needs. I have put a lot of work into the scripts, so it would be a shame to not use them.

**Comment by justinglock40** [comment]
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/1ccb8f91-881d-48fe-904a-4eea34a6aa79)


Getting this error in Sonarr using the scripts

**Comment by RandomNinjaAtk** [comment]
Looks like you renamed your app in the settings and are not using the default "Sonarr". The scripts are expecting the app names to be Radarr, Sonarr, and Lidarr.

**Comment by justinglock40** [comment]
Where in the setting would the name be changed? I don't recall ever doing that

**Comment by justinglock40** [comment]
Figured it out. It's because the default LSIO latest tag is v3 and I was using v4 with your images.

**Comment by justinglock40** [comment]
Is there a way to disable the extra stuff like Youtube. I really on use the notifier

**Comment by RandomNinjaAtk** [comment]
No there isn't a way to disable/customize anything, like I said in my first message on this issue.  Unless you decide to modify the scripts and remove the ones you don't want.

However, the YouTube series downloader will only process matching series, so if you don't have any YouTube series, it'll run, but not do anything.

For Plex notify to work, you need to add the variables that are required, check the retired container for the documentation.

**Comment by justinglock40** [comment]
Ok I'll look and see what I can come up with

**Comment by RandomNinjaAtk** [comment]
@karbowiak @justinglock40 

Here are the instructions, only applicable to Sonarr at this time.
https://github.com/RandomNinjaAtk/arr-scripts/tree/main/sonarr#readme

See if that works for ya!

**Comment by RandomNinjaAtk** [comment]
https://github.com/RandomNinjaAtk/arr-scripts/tree/main/sabnzbd#readme

**Comment by RandomNinjaAtk** [comment]
[#](https://github.com/RandomNinjaAtk/arr-scripts/tree/main/radarr#readme)

**Comment by RandomNinjaAtk** [comment]
More info: https://github.com/RandomNinjaAtk/arr-scripts#arr-scripts

**Comment by joshoram80** [comment]
```
07/14/2023 4:25:57 PM
************ install packages ************
07/14/2023 4:25:57 PM
bash: line 5: apk: command not found
07/14/2023 4:25:57 PM
bash: line 35: pip3: command not found
07/14/2023 4:25:57 PM
bash: line 41: apk: command not found
07/14/2023 4:25:57 PM
Download QueueCleaner service...
```

```
07/14/2023 4:25:58 PM
./run: line 120: xq: command not found
07/14/2023 4:25:58 PM
2023-07-14 16:25:58 :: AutoExtras :: 1.2 :: Sleeping (infinity)
07/14/2023 4:25:58 PM
./run: line 28: xq: command not found
07/14/2023 4:25:58 PM
./run: line 28: xq: command not found
07/14/2023 4:25:58 PM
./run: line 28: xq: command not found
07/14/2023 4:25:58 PM
./run: line 29: xq: command not found
07/14/2023 4:25:58 PM
./run: line 29: xq: command not found
07/14/2023 4:25:58 PM
./run: line 29: xq: command not found
07/14/2023 4:25:58 PM
2023-07-14 16:25:58 :: QueueCleaner :: 1.0.6 :: ERROR :: Arr app not detected, exiting...
07/14/2023 4:25:58 PM
./run: line 30: xq: command not found
07/14/2023 4:25:58 PM
./run: line 30: xq: command not found
07/14/2023 4:25:59 PM
./run: line 30: xq: command not found
07/14/2023 4:25:59 PM
2023-07-14 16:25:59 :: Recyclarr :: 1.3 :: Updating Sonarr via Recyclarr
07/14/2023 4:25:59 PM
./run: line 82: /recyclarr/recyclarr: No such file or directory
07/14/2023 4:25:59 PM
2023-07-14 16:25:59 :: AutoConfig :: 1.2 :: Using custom Sonarr Naming (/config/extended/naming.json)...
07/14/2023 4:25:59 PM
2023-07-14 16:25:59 :: Recyclarr :: 1.3 :: Complete
07/14/2023 4:25:59 PM
2023-07-14 16:25:59 :: Recyclarr :: 1.3 :: Script sleeping for 4 hours...
```

This is on a brand new install, no existing files or anything, :latest Linuxserver sonarr image. I have checked and the instance name is "Sonarr"

**Comment by RandomNinjaAtk** [comment]
@joshoram80 

Doesn't look like you followed the instructions correctly.

Double check the requirements and double check that you correctly followed the instructions.

There is nothing to fix, because it's chased by user error.

**Comment by joshoram80** [comment]
It was because the docker image for Sonarr and Radarr was :latest and not :develop

Did not see `Version Tag: develop (only if migrating from original sonarr-extended container...)`

**Comment by adocampo** [comment]
silly question: should I remove the `scripts_init.bash` script from `custom-cont-init.d` folder after intallation?

**Comment by justinglock40** [comment]
No. You'll need it in the future for updates
