### ISSUE TITLE
[feature request] Lidarr - Fallback to YouTube if deezer album not found.

### ISSUE THREAD

**Issue by jasperaelvoet** [RandomNinjaAtk/arr-scripts#58]
Feature:
If no matching albums are found on deezer the script will try to download the individual tracks of the album via YouTube.
Optimally it will retry downloading from deezer, with the same retry time for not found albums.

**Comment by RandomNinjaAtk** [comment]
If you want to use youtube, just remove your ARL token, and you'll get versions form youtube... 

As far as building a full feature to do this, I'm not likely to take the time to do it... PR welcome!

**Comment by RandomNinjaAtk** [comment]
Fallback implemented but not tested, give it a try.

**Comment by jasperaelvoet** [comment]
Freyr uses deezer to get the track list, so if the album is not on deezer it will still fail. I will be opening a PR with once I have a working implementation of this.

**Comment by RandomNinjaAtk** [comment]
I did a quick review and the biggest issue I see is that your querying musicbrainz api for data, and we cannot do that... 

Earlier versions of the scripts would do that and it had to be removed due to complaints from musicbrainz.org that were incorrectly directed at the Lidarr team.

Some functionality was removed as a result and I was able to make it some of it work using built-in lidarr features to maintain the majority of functionality that had to be ripped out...

So if you can find a way to make it work without querying musicbrainz, I'll consider merging it, but because of previous tensions, I cannot merge it because it reaches out to musicbrainz.org and they don't want to take on the traffic.

You can see here, where the processes/code was removed: https://github.com/RandomNinjaAtk/docker-lidarr-extended/commit/a9be3943ac592fbe658e81b6b120667ad58df25f
