### ISSUE TITLE
[BUG] - sabnzbd - ffprobe not found

### ISSUE THREAD

**Issue by realcanadrian** [RandomNinjaAtk/arr-scripts#74]
**Application**
SABnzbd

**Host platform**
Unraid

**Script**
video.bash

**Script Version**
1.0.5

**Describe the bug**
When post-processing video, the script can not find ffprobe. 

**To Reproduce**
1. Configure post-processing scripts
2. Download video with SAB
3. Wait for post-processing to complete

**Expected behavior**
Successful completion of the steps in video.bash

**Logs/Screenshots**
Error message:
```
2023-09-02 10:14:42 :: Video :: 1.0.5 :: SABnzbd Job: video.file.name
2023-09-02 10:14:42 :: Video :: 1.0.5 :: SABnzbd Category: tv
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Script Versiion: 1.0.5
2023-09-02 10:14:42 :: Video :: 1.0.5 :: CONFIGURATION VERIFICATION
2023-09-02 10:14:42 :: Video :: 1.0.5 :: ##########################
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Preferred Audio/Subtitle Languages: eng
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Require Matching Language :: Enabled
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Sickbeard MP4 Automator (SMA): ENABLED
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Sickbeard MP4 Automator (SMA): Tagging: ENABLED
2023-09-02 10:14:42 :: Video :: 1.0.5 :: Processing 1 video files...
2023-09-02 10:14:42 :: Video :: 1.0.5 :: 1 of 1 :: Processing video.file.name.mkv
/config/scripts/video.bash: line 66: ffprobe: command not found
```

**Additional context**
Host OS: Unraid 6.12.6
SAB image: lscr.io/linuxserver/sabnzbd:latest 4.0.3-ls124
Docker mods: linuxserver/mods:sabnzbd-par2cmdline-turbo

**THANK YOU!!!**

**Comment by RandomNinjaAtk** [comment]
So, this is an indication that the init script did not run and install required packages. Re-read the setup instructions and double/triple check that you set it up correctly...

There is no further action needed, because this is a user configuration issue.... If you restart the container and watch the container logs as it starts, if you do not see it install packages, then its not working...

Docs: https://github.com/RandomNinjaAtk/arr-scripts/tree/main/sabnzbd#/readme.md

**Comment by realcanadrian** [comment]
I actually just found out that what is happening is all the containers I set up since I moved from Ubuntu to Unraid aren't running the custom init script for some reason. I set it up the same as I did on Ubuntu and it was working there, but on Unraid the scripts just don't run automatically when the container does. If I open a terminal inside the container and manually run the init script, then the rest of the scripts start working. Any idea why this isn't working when setting up on Unraid vs the exact same setup on Ubuntu?

**Comment by RandomNinjaAtk** [comment]
I'd say it still indicates a configuration issue. For reference, my host is an UNRAID system, so I know it works...  Honeslty can't help you any further than that...

I noticed that your using a docker mod, so I honestly don't know if that could cause an issue because I don't use any mods....

Sorry cannot be any further help.... Please post back here if you figure it out...

You may want to try to setup a new container, no previous configuration, no docker mod, and see if it works as designed...

**Comment by realcanadrian** [comment]
That's fair enough. At least I have it working now, even if I needed to intervene manually. Thanks so much for these scripts. I'll let you know if I do figure out what the problem might be.
